// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packet_type.proto

package com.techstart.protobuf.ecommerce;

public final class PacketTypeOuterClass {
  private PacketTypeOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021packet_type.proto\022\tecommerce*:\n\nPacket" +
      "Type\022\017\n\013PACKET_NONE\020\000\022\010\n\004DATA\020\001\022\021\n\rSYSTE" +
      "M_STATUS\020\002B$\n com.techstart.protobuf.eco" +
      "mmerceP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
