// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packet_type.proto

package com.techstart.protobuf.ecommerce;

/**
 * Protobuf enum {@code ecommerce.PacketType}
 */
public enum PacketType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>PACKET_NONE = 0;</code>
   */
  PACKET_NONE(0),
  /**
   * <code>DATA = 1;</code>
   */
  DATA(1),
  /**
   * <code>SYSTEM_STATUS = 2;</code>
   */
  SYSTEM_STATUS(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>PACKET_NONE = 0;</code>
   */
  public static final int PACKET_NONE_VALUE = 0;
  /**
   * <code>DATA = 1;</code>
   */
  public static final int DATA_VALUE = 1;
  /**
   * <code>SYSTEM_STATUS = 2;</code>
   */
  public static final int SYSTEM_STATUS_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static PacketType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static PacketType forNumber(int value) {
    switch (value) {
      case 0: return PACKET_NONE;
      case 1: return DATA;
      case 2: return SYSTEM_STATUS;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<PacketType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      PacketType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<PacketType>() {
          public PacketType findValueByNumber(int number) {
            return PacketType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.techstart.protobuf.ecommerce.PacketTypeOuterClass.getDescriptor().getEnumTypes().get(0);
  }

  private static final PacketType[] VALUES = values();

  public static PacketType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private PacketType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:ecommerce.PacketType)
}

