// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: ecommerce/data_response.proto


#include "ecommerce/data_response.pb.h"
#include "ecommerce/data_response.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace ecommerce {

static const char* DataService_method_names[] = {
  "/ecommerce.DataService/getData",
};

std::unique_ptr< DataService::Stub> DataService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< DataService::Stub> stub(new DataService::Stub(channel));
  return stub;
}

DataService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_getData_(DataService_method_names[0], ::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  {}

::grpc::ClientReader< ::ecommerce::DataResponse>* DataService::Stub::getDataRaw(::grpc::ClientContext* context, const ::ecommerce::DataRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::ecommerce::DataResponse>::Create(channel_.get(), rpcmethod_getData_, context, request);
}

void DataService::Stub::experimental_async::getData(::grpc::ClientContext* context, const ::ecommerce::DataRequest* request, ::grpc::experimental::ClientReadReactor< ::ecommerce::DataResponse>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::ecommerce::DataResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_getData_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::ecommerce::DataResponse>* DataService::Stub::AsyncgetDataRaw(::grpc::ClientContext* context, const ::ecommerce::DataRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::ecommerce::DataResponse>::Create(channel_.get(), cq, rpcmethod_getData_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::ecommerce::DataResponse>* DataService::Stub::PrepareAsyncgetDataRaw(::grpc::ClientContext* context, const ::ecommerce::DataRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::ecommerce::DataResponse>::Create(channel_.get(), cq, rpcmethod_getData_, context, request, false, nullptr);
}

DataService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      DataService_method_names[0],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< DataService::Service, ::ecommerce::DataRequest, ::ecommerce::DataResponse>(
          [](DataService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ecommerce::DataRequest* req,
             ::grpc::ServerWriter<::ecommerce::DataResponse>* writer) {
               return service->getData(ctx, req, writer);
             }, this)));
}

DataService::Service::~Service() {
}

::grpc::Status DataService::Service::getData(::grpc::ServerContext* context, const ::ecommerce::DataRequest* request, ::grpc::ServerWriter< ::ecommerce::DataResponse>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace ecommerce

